### ISSUE TITLE
How to increase default number of iterations in fitSSM

### ISSUE THREAD

**Issue by RajarshiBhadra** [helske/KFAS#11]
The fitSSM function looks like this

`fitSSM(model, inits, updatefn, checkfn, update_args = NULL, ...)`

Writing the fitSSM in this way 

`fitSSM(inits = inits, model = modelH, method = "BFGS")` 

helps control the method of optim. What further arguement should be added to change the number of iterations as well if I want more iterations than the default 100 which BFGS provides

**Comment by helske** [comment]
Just like you can pass the `method` argument to  `optim`, you can pass all the other arguments as well, so in this case if you check the documentation of the `optim`, you see that you need to use `control` argument which is a list of several options to `optim`, like this:
```
fitSSM(inits = inits, model = modelH, method = "BFGS", control = list(maxit = 1000)
```
