### ISSUE TITLE
Want to Omit Observations at Beginning of Series when Calculating Log-Likelihood

### ISSUE THREAD

**Issue by chuckcoleman** [helske/KFAS#18]
When estimating MA models, it is often necessary to effectively throw away observations at the beginning of the time series.  (There is an extensive literature about this.)  I've been estimating IMA(1,1) models as the sum of 2 unobserved AR(1) processes with diffuse initialization.  The results from using all of the data to maximize the likelihood are ludicrous. The first few estimates are way off and the MA coefficient is nonsensical.  Since those first few estimates depend on the estimated parameters, I can't simply throw them away.  I'd like to keep those estimates, but not use them in the likelihood.

I tried to tinker with the source code, but it's a little beyond me. It looks like the ymiss used for the likelihood calculation has to have the desired number of values flagged at the beginning.  I've attached a modification of gloglik.f95 to show what I mean.

[gloglik.zip](https://github.com/helske/KFAS/files/721462/gloglik.zip)

**Comment by helske** [comment]
Without seeing any reproducible code, I am not sure what to think of this. I am quite sure that the general handling of missing observations is correct in KFAS, as shown by numerous tests, examples etc. To be honest I am not sure what you are trying to achieve, if you don't want to use the first observations in the estimation of the model parameters, you can just set them to NA, fit the model, and reinsert the values?

It sounds that you are building your IMA(1,1) model using `SSMcustom` part, but you could make that model more easily with `SSMarima` as well? My first guess is that you have mispecified your model so that it is not identifiable (e.g. you have extra diffuse intercept term).

**Comment by chuckcoleman** [comment]
Hi Jouni,
I think I overreacted a bit.  I redid the model using SSMarima.  (I was using code for an earlier version of KFAS.)  I saw a positive MA coefficient that I should have expected.  What's really interesting is that I chose this series for testing because X13-ARIMA-SEATS didn't identify any outliers.  Package tsoutliers identified an outlier where I wasn't expecting any.  The problem I have with the model is that there is a burn-in period: 1 or 2 observations.  The first residual is wild, the second is in line with the others, but suspiciously round.  I have attached the code and a data file.
I'm sorry it's taken so long to write.  Between sickness and resistance to Trump, time has been scarce.  I live near Washington, DC, so life has acquired a new rhythm: eat, sleep, work, eat, sleep, work, resist, eat, sleep, resist.  My Facebook has been burning with notifications.  I'm a federal employee and we're all scared of what 45 will do.  I work for the Census Bureau.  45 issued an executive order to do something we normally do and to review the long-form census.  The fool doesn't understand that the long-form census was discontinued in 2010.  Now, we have the American Community Survey, which some Republicans want to turn into a voluntary response survey.  Canada's Harper government tried that out of the blue and ended up wasting time and money to produce meaningless numbers due to very high nonresponse.  The Trudeau government quickly reversed that.
I visited Goddard Space Flight Center yesterday and heard about EEMD.  I do seasonal adjustment at work and hope to organize our next seasonal adjustment workshop.  Last year, we only heard about X13 and a few extensions.  I saw that you coauthored a package that does EEMD, so I may be in touch with you about it.  The conference is for official statistics workers and I think we should hear what other fields are doing.
Regards,Chuck 

    On Thursday, January 26, 2017 1:41 AM, Jouni Helske <notifications@github.com> wrote:
 

 Without seeing any reproducible code, I am not sure what to think of this. I am quite sure that the general handling of missing observations is correct in KFAS, as shown by numerous tests, examples etc. To be honest I am not sure what you are trying to achieve, if you don't want to use the first observations in the estimation of the model parameters, you can just set them to NA, fit the model, and reinsert the values?It sounds that you are building your IMA(1,1) model using SSMcustom part, but you could make that model more easily with SSMarima as well? My first guess is that you have mispecified your model so that it is not identifiable (e.g. you have extra diffuse intercept term).—

**Comment by helske** [comment]
Just deleted a message which I suppose was meant only for an email communication but ended up here as well. I guess this issue is now sorted so closing.
