### ISSUE TITLE
SSMcustom() does not return valid SSModel

### ISSUE THREAD

**Issue by mdbauer** [helske/KFAS#23]
SSMcustom() returns an object that does not have class "SSModel". Therefore is.SSModel() returns FALSE and  KFS aborts with error. 

It looks like SSMarima(), SSMcycle(), SSMregression() have the same problem.

**Comment by helske** [comment]
You are not supposed to use those functions independently, but inside of SSModel call instead. Like `SSModel(y ~ SSMcustom(...), H = 1)`. See vignette or help pages for proper examples.

**Comment by mdbauer** [comment]
Sorry about that, thank you very much.
