### ISSUE TITLE
Filtered estimator VS. one-step ahead predictor

### ISSUE THREAD

**Issue by yuanyuan2319** [helske/KFAS#24]
Hello, I have two questions about KFAS. The first one is about filtered estimator(a_t|t) versus one-step ahead predictor(a_t). 

In Time Series Analysis by State Space Methods by Durbin and Koopman, a_t is the one step ahead predictor of alpha_t, a_t|t is the filtered estimator of alpha_t. In other words, a_t is E(alpha_t | y_t-1, ..., y_1), a_t|t is E(alpha_t | y_t, ..., y_1). For local level model, a_t+1 = a_t|t. But for general linear Gaussian, a_t|t != a_t+1.

My question is: which one is the a_t|t in KFS results? I only find two state estimations, a and alphahat. And a is a_t, alphahat is smoothed one. It seems you take a also as filtered estimation. But I think they are different?

Secondly, I want to confirm the definition of univariate approach.  I am using Kalman filter to perform Fama/French factor analysis on stock returns, so the model would be y_t = alpha + beta1_t*factor1_t + beta2_t*factor2_t + beta3_t*factor3_t + error_t (betas are state variables, y_t is a 1*1 vector at time t). This is a univariate model, right?

Thank you very much for your time! Look forward to your reply.

**Comment by helske** [comment]
Currently `KFS` only returns smoothed estimates (`alphahat`) and one-step-ahead predictions (`a`). Originally I left out the output of filtered estimates, as I personally didn't need those, and after that there has been surprisingly little questions about these, so I haven't bothered to add those. But now I did this, the latest version of KFAS in github now returns also filtered estimates `att` and `Ptt` for Gaussian models (for simplicity the diffuse part of P is disregarded as that is generally not that interesting).

**Comment by yuanyuan2319** [comment]
Hi Helske, thanks for your update. I will ask you if I have further questions on package.
