### ISSUE TITLE
Univariate approach for maximum loglikelihood in multivariate state space models

### ISSUE THREAD

**Issue by rondel67** [helske/KFAS#37]
Is it possible to calculate maximum loglikelihood for each time series in multivariate  state space models in KFAS? If so, how could it be done in KFAS?
Koopman’s STAMP software provides “univariate” AIC for each time series in multivariate state space models so “univariate” maximum loglikelihood seems to be calculated there. I would like to replicate this in KFAS.

**Comment by helske** [comment]
Using the output from KFS you should be able to compute "univariate likelihoods" manually using v and F components of the output.

**Comment by rondel67** [comment]
Thank you
