### ISSUE TITLE
Can't calculate multivariate time-series

### ISSUE THREAD

**Issue by ymatsumotomatsu** [helske/KFAS#43]
Hello. I've been working on estimating coordinates with kalman filter.

I can't calculate estimated values of one of multivariate time-series. Time-series have no missing value and its sizes are same.

Code:
library(KFAS) 

cam1 <- read.table("cam1.dat", header = T)
cam2 <- read.table("cam2.dat", header = T)

x1 <- ts(cam1$x)
x2 <- ts(cam2$x)

modSUTSE <- SSModel(cbind(x1,x2) ~
                      SSMtrend(1, Q = matrix(NA,2,2), type = "distinct"), H = matrix(NA,2,2))
fitSUTSE <- fitSSM(modSUTSE, numeric(6), method="BFGS")
kfsSUTSE <- KFS(fitSUTSE$model)

afilt <- kfsSUTSE$alphahat[1:554,]

plot(x1,lty=3,xlab="フレーム",ylab="距離")
lines(afilt[,1],lwd=2)

plot(x2,lty=3,xlab="フレーム",ylab="距離")
lines(afilt[,2],lwd=2)

Result:
![Rplot02](https://user-images.githubusercontent.com/51198984/77306993-d1e27a00-6d3b-11ea-90a0-2facd842498c.png) ![Rplot03](https://user-images.githubusercontent.com/51198984/77306997-d27b1080-6d3b-11ea-89bd-a6da3e1e9976.png)

And, I can't calculate if I replace x1 with x2 as well.
![Rplot04](https://user-images.githubusercontent.com/51198984/77307474-a9a74b00-6d3c-11ea-8b7c-959630b06575.png) ![Rplot05](https://user-images.githubusercontent.com/51198984/77307478-aa3fe180-6d3c-11ea-9bc4-b960112b94b6.png)

How should I do this?

**Comment by helske** [comment]
Sorry, I would need reproducible example to understand what is wrong with your results. You might want to test different initial values to `fitSSM` to see if the results depend on those.

**Comment by ymatsumotomatsu** [comment]
This is data. Please rename .txt to .dat and run by code I pasted.
[cam1.txt](https://github.com/helske/KFAS/files/4469234/cam1.txt)
[cam2.txt](https://github.com/helske/KFAS/files/4469233/cam2.txt)

**Comment by helske** [comment]
Different initial values help. Test for example ` fitSSM(modSUTSE, rep(-2,6), method="BFGS")` and you get better optimum and the results look more reasonable.

**Comment by helske** [comment]
I guess this is solved?
