### ISSUE TITLE
space and time prediction

### ISSUE THREAD

**Issue by sue-shine** [helske/KFAS#55]
hi, helske
Whether the KFAS package can be used for two-dimensional variations in space and time, the examples given here are only time series of variations in time. If I want to show the pattern of location changes at different times on the map (add latitude and longitude to represent the geographical location), What should I do?
Looking forward to your reply, Thanks!

**Comment by sue-shine** [comment]
hi, helske
Whether the KFAS package can be used for two-dimensional variations in space and time, the examples given here are only time series of variations in time. If I want to show the pattern of location changes at different times on the map (add latitude and longitude to represent the geographical location), What should I do?
Looking forward to your reply, Thanks!

**Comment by sue-shine** [comment]
Hi, sorry to bother you, I uploaded a sample data to express the problem I want to solve. I looked up many related information about the package, but  but still seems unable to solve my problem. Would you mind using the sample data to help me out.
The data included sample points of known latitude and longitude in an area (two years), each with a population and number of cases, assuming that te number of cases follows the Poisson distribution. Now I want to use these sample point data to predict the incidence in whole region so that trends can be plotted. The data is attached, I will appreciate your help!
with best wishes!
[sample_data.xlsx](https://github.com/helske/KFAS/files/5677068/sample_data.xlsx)
[example.docx](https://github.com/helske/KFAS/files/5677069/example.docx)

**Comment by helske** [comment]
Oh now I see, you seem to have spatio-temporal problem, so you probably need to use something else than state space modelling with KFAS. You might try something like INLA for this kind of data.

**Comment by sue-shine** [comment]
But I have read your article named KFAS: Exponential Family State Space Models in R, and it has this formula:
yt,i= Zt,i*αt,i+?t,i,              i = 1, . . . , pt,  t = 1, . . . , n,
αt,i+1= αt,i,                       i = 1, . . . , pt− 1,
αt+1,1= Tt*αt,pt+ Rt*ηt,   t = 1, . . . , n,
Can the letter i here be thought of as a different latitude and longitude position, and y  is a vector, so can it represent the observations at different places at different times. Now I want to do this in a more dynamic way than INLA, I wonder if KFAS might be a good choice.

**Comment by helske** [comment]
Oh yes, sorry, I just quickly glanced your attachments, you are right that is, of course, possible if you have fixed locations.

**Comment by sue-shine** [comment]
I wonder if you've ever worked with similar data before,  I am very sorry that I have encountered difficulties in processing data.

**Comment by helske** [comment]
Not really, but as said, the modelling itself does not care what the data represents so in that sense it is just a matter of defining the relevant system matrices according to your needs.

**Comment by sue-shine** [comment]
yeah, That's the point. Would it be convenient for you to run the code with the sample data if you have time?

**Comment by helske** [comment]
Sorry, I do not have time for such.

In general, the GitHub issue tracker is meant mainly for reporting bugs and feature requests, for general questions about the state space modelling I suggest for example [Cross Validated](https://stats.stackexchange.com/).

**Comment by sue-shine** [comment]
Ok, thanks for your feedback!

**Comment by sue-shine** [comment]
Hi,sorry to bother you again.
In the illustration section of the article "KFAS: Exponential Family State Space Models in R".  I have a question about the following code:
pred <- predict(fit$model,
+  newdata = SSModel(ts(matrix(NA, 6, 4), start = 2008) ~ -1 +
+  SSMcustom(Z = fit$model$Z, T = fit$model$T, R = fit$model$R,
+  Q = fit$model$Q), u = 1, distribution = "poisson"),
+  interval = "confidence", nsim = 10000)

What does u=1 mean?

**Comment by sue-shine** [comment]
I want to predict more points in time (3600 points) from 1782 points in time, but the code reported an error:
> n1<-as.ts(n1)
> t2<-as.ts(t2)
> mymodel<-SSModel(n1~
+             SSMtrend(2,Q=list(matrix(NA),matrix(0)))+
+   SSMcustom(Z = matrix(c(1, 0), 1, 2), T=diag(0, 2),
+             R= matrix(c(1, 0), 2, 1), Q = matrix(NA),
+             P1 = matrix(NA,2,2)), distribution = "poisson",
+             u =t2 )
> update<- function(pars, model) {
+        model["Q", etas = "level"] <- exp(pars[1])
+        model["Q", etas = "custom"]<- exp(pars[2]) 
+        model["P1", states = "custom"] <- exp(pars[2])
+        model
+ }
> fit_poisson <- fitSSM(mymodel, c(1,1), update,
+                        method = "BFGS")
##Warning messages:
1: In logLik.SSModel(object = model, check.model = FALSE, theta = theta,  :
  Gaussian approximation failed due to non-finite value in linear predictor.
2: In logLik.SSModel(object = model, check.model = FALSE, theta = theta,  :
  Gaussian approximation failed due to non-finite value in linear predictor.
3: In logLik.SSModel(object = model, check.model = FALSE, theta = theta,  :
  Gaussian approximation failed due to non-finite value in linear predictor.
4: In logLik.SSModel(object = model, check.model = FALSE, theta = theta,  :
  Gaussian approximation failed due to non-finite value in linear predictor.
5: In logLik.SSModel(object = model, check.model = FALSE, theta = theta,  :
  Gaussian approximation failed due to non-finite value in linear predictor.
> pred <- predict(fit_poisson$model,
+         newdata = SSModel(rep(NA,3600) ~ -1 +
+           SSMcustom(Z = fit_poisson$model$Z, T = fit_poisson$model$T,
+                     R = fit_poisson$model$R,
+           Q = fit_poisson$model$Q), u =matrix(NA,3600,3600),distribution = "poisson"),
+                 interval = "confidence")
##Error in is.SSModel(newdata, na.check = TRUE, return.logical = FALSE) : 
  System matrices (excluding Z) contain NA or infinite values, covariance matrices contain values larger than 1e+07

Could you please help to check it, Thank you very much
