### ISSUE TITLE
Standardized residuals calculated from the KFS output

### ISSUE THREAD

**Issue by suprajamalladi** [helske/KFAS#57]
![ab](https://user-images.githubusercontent.com/66227256/96348427-99f3a900-1076-11eb-9070-e7571f2145d5.jpg)

In the attached page from the KFAS package description, the standardized state and observation residuals calculated using the "rstandard" function have different formulas from those in Durbin and Koopman (2012). 
 Below are the formulas for the standardized residuals from Durbin and Koopman(2012):
![image](https://user-images.githubusercontent.com/66227256/96348803-68301180-1079-11eb-88f1-a266d2a85f04.png)

I would like to know why they are different? Also, is there a way I can get the residuals from KFS using the exact same formulas as in the Durbin and Koopman(2012) book?

**Comment by helske** [comment]
The formulas are same, the DK formulas are just stated in terms of univariate states/series where it makes sense to write square root of variance. The formula for the observation residuals in KFAS is just written in a different way as the formula in DK is for Gaussian models whereas the one in the KFAS docs is applicable also for non-Gaussian models.

**Comment by suprajamalladi** [comment]
thank you very much for your response!
