### ISSUE TITLE
exact diffuse initialization

### ISSUE THREAD

**Issue by suprajamalladi** [helske/KFAS#59]
can you please explain the difference between exact diffuse , partial diffuse and nondiffuse initialization? or can you give me a reference paper that I can read to know more?

**Comment by helske** [comment]
For diffuse initialization, the prior distribution of the states at time 1 is assumed to be N(0, infinity * I), for nondiffuse initialization the covariance matrix can be arbitrary, and for partially diffuse some of the elements of the state vector are given diffuse initialization and for the rest normal initialization. You can find more in several papers by Durbin and Koopman (also their book), e.g. 

Koopman, S.J. and Durbin J. (2000). Fast filtering and smoothing for non-stationary time series models, Journal of American Statistical Assosiation, 92, 1630-38.

Koopman, S.J. and Durbin J. (2012). Time Series Analysis by State Space Methods. Second edition. Oxford: Oxford University Press.

Koopman, S.J. and Durbin J. (2003). Filtering and smoothing of state vector for diffuse state space models, Journal of Time Series Analysis, Vol. 24, No. 1.

**Comment by suprajamalladi** [comment]
thank you very much for your response!
