### ISSUE TITLE
Change .f95 suffix to .f90

### ISSUE THREAD

**Issue by Beliavsky** [helske/KFAS#68]
Please consider changing the source file suffixes from .f95 to .f90.
The .f90 suffix means that the source code is free format, not that
the code conforms to the Fortran 90 standard. Code that uses the .f90
suffix can use features from any Fortran standard. All Fortran
compilers recognize .f90 as a suffix indicating free source form, but
some may not recognize a suffix such as .f95, .f03, .f08, or .f18. 
Some users may have build tools that do not recognize suffixes other
than .f90. Most Fortran source code on GitHub that uses features from
a standard more recent than Fortran 90 still uses the .f90 suffix.

**Comment by helske** [comment]
Thanks for the suggestion and insights, I can't remember why I originally chose .f95. I see no reason why not to make the change if that is helpful in some cases.
