### ISSUE TITLE
Problem to set a state space model

### ISSUE THREAD

**Issue by rodrigopmaranhao** [helske/KFAS#7]
Hi. I'm having some issues to set my SSMcustom.

Here is what I'm doing:
<pre>
y=base1$close
Z=array(rbind(t(base2$close),t(rep(1,length(y)))),dim=c(1,2,length(y)))
matT=diag(1,2,2)
matR=matT
Q=matT*0.01
modeloCustom=SSMcustom(Z=Z,T=matT,R=matR,Q=Q,P1inf=diag(1,2,2),n=length(y))
</pre>

However, if I check
<pre>
is.SSModel(modeloCustom)
</pre>
It returns false.

Also, if I  try:
<pre>
modelo=SSModel(y~-1+modeloCustom)
</pre>

It shows:
<pre>
> modelo=SSModel(y~-1+modeloCustom)
Error in model.frame.default(formula = y ~ -1 + modeloCustom, na.action = na.pass) : 
  invalid type (list) for variable 'modeloCustom'
</pre>

What I'm doing wrong? Someone could help me?

Thank you.

**Comment by helske** [comment]
Outputs from `SSMcustom`, `SSMregression` etc. are just lists, so `is.SSModel(modeloCustom)` returning `FALSE` is correct. Those functions are meant to be used inside `SSModel` call, like this:
```
 modelo <- SSModel(y~ -1 + SSMcustom(Z=Z,T=matT,R=matR,Q=Q,P1inf=diag(1,2,2)))
```
You can see multiple examples in the main help page of the package (``?KFAS``).
